config/routes.rb
Rails.application.routes.draw do

  get '/' => 'site#home'
  resources :people do
    resources :phones
    resources :emails
  end

end

app/models/email.rb
class Email < ActiveRecord::Base
  belongs_to :person
  validates :address, 
    presence: true,
    format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  def display_text
    self.address
  end
end

app/models/person.rb
class Person < ActiveRecord::Base
  has_many :phones, :dependent => :delete_all
  has_many :emails, :dependent => :delete_all

  validates :name,
    presence: true,
    uniqueness: true,
    length: { maximum: 30 }

  def full_name
    "#{self.name}" + (self.address.present? ? ". Addr: #{self.address}" : "")
  end

end

app/models/phone.rb
class Phone < ActiveRecord::Base
  belongs_to :person
  validates :address, 
    presence: true,
    format: { with: /\A[0-9\.\(\)\+-]+\z/i }

  def display_text
    self.address
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  def index
    @person = Person.find(params[:person_id])
    @emails = @person.emails.all
  end

  def new
    @person = Person.find(params[:person_id])
    @email = @person.emails.new
  end

  def create
    @person = Person.find(params[:person_id])
    @email = @person.emails.new(edit_params)

    if @email.save
      redirect_to(action: 'index')
    end
  end

  def edit
    @person = Person.find(params[:person_id])
    @email = @person.emails.find(params[:id])
  end

  def update
    @person = Person.find(params[:person_id])
    @email = @person.emails.find(params[:id])
    @email.update_attributes(edit_params)

    if @email.save
      flash[:notice] = "Data updated sccessfully"
      redirect_to(action: 'index')
    else
      flash[:error] = "Please, check errors"
      render('edit')
    end
  end

  def destroy
    @person = Person.find(params[:person_id])
    @email = @person.emails.find(params[:id])
    @email.destroy
    redirect_to(action: 'index')
  end

  def show
    @person = Person.find(params[:person_id])
    @email = @person.emails.find(params[:id])
  end

  private

  def edit_params
    params.require(:email).permit(:hours, :minutes, :date)
  end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all.order(:name)
  end

  def show
    @person = Person.find(params[:id]) # raises an exception
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(edit_params)

    if @person.save
      redirect_to(action: 'index')
      flash[:notice] = "Person created sccessfully"
    else
      flash[:error] = "Please, check errors"
      render('new')
    end
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])
    @person.update_attributes(edit_params)

    if @person.save
      flash[:notice] = "Data updated sccessfully"
      redirect_to(action: 'index')
    else
      flash[:error] = "Please, check errors"
      render('edit')
    end
  end

  def destroy
    @person = Person.find(params[:id])
    @person.destroy
    redirect_to(action: 'index')
  end

  private

  def edit_params
    params.require(:person).permit(:name, :address)
  end
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  def index
    @person = Person.find(params[:person_id])
    @phones = @person.phones.all
  end

  def new
    @person = Person.find(params[:person_id])
    @phone = @person.phones.new
  end

  def create
    @person = Person.find(params[:person_id])
    @phone = @person.phones.new(edit_params)

    if @phone.save
      redirect_to(action: 'index')
    end
  end

  def edit
    @person = Person.find(params[:person_id])
    @phone = @person.phones.find(params[:id])
  end

  def update
    @person = Person.find(params[:person_id])
    @phone = @person.phones.find(params[:id])
    @phone.update_attributes(edit_params)

    if @phone.save
      flash[:notice] = "Data updated sccessfully"
      redirect_to(action: 'index')
    else
      flash[:error] = "Please, check errors"
      render('edit')
    end
  end

  def destroy
    @person = Person.find(params[:person_id])
    @phone = @person.phones.find(params[:id])
    @phone.destroy
    redirect_to(action: 'index')
  end

  def show
    @person = Person.find(params[:person_id])
    @phone = @person.phones.find(params[:id])
  end

  private

  def edit_params
    params.require(:phone).permit(:hours, :minutes, :date)
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def home
    @people = Person.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Address Book</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <h1>Address Book</h1>
    
    <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: name %>
    <% end -%>
    
  </header>

<%= yield %>

  <footer>
    <h4>
      <div class="new_item button_actions"><%= link_to("Home",'/') %></div>
      <div class="all_items button_actions"><%= link_to("People",people_path) %></div>
    </h4>
  </footer>
</body>
</html>

app/views/people/_form.html.erb
<%= form_for @person, :html => { :multipart => true } do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, size: 12 %>
  <br>
  <%= f.label :address %>
  <%= f.text_field :address, size: 24 %>
  <br>

  <%= f.submit 'Save' %>
  <%= link_to("Cancel",people_path) %>

<% end %>

app/views/people/edit.html.erb
<% if @person.errors.any? %>
  <ul>
    <% @person.errors.full_messages.each do |error_msg| %>
    <li><%= error_msg %></li>
    <% end %>
  </ul>
<% end %>

<h2>Edit person</h2>

<%= render 'form' %>

app/views/people/index.html.erb
<h2>People listing</h2>

<%= render 'shared/people_list' %>

app/views/people/new.html.erb
<% if @person.errors.any? %>
  <ul>
    <% @person.errors.full_messages.each do |error_msg| %>
    <li><%= error_msg %></li>
    <% end %>
  </ul>
<% end %>

<%= render 'form' %>

app/views/people/show.html.erb
<h2>Info about ...</h2>
<%=@person.full_name%>

app/views/phones/_form.html.erb
<%= form_for [@person, @phone] do |f| %>
  <%= f.label :address %>
  <%= f.text_field :address, size: 48 %>
  <br>

  <%= f.submit 'Save' %>
  <%= link_to("Cancel",person_phones_path) %>
<% end %>

app/views/phones/edit.html.erb
<% if @phone.errors.any? %>
  <ul>
    <% @phone.errors.full_messages.each do |error_msg| %>
    <li><%= error_msg %></li>
    <% end %>
  </ul>
<% end %>

<h2>Edit phone for <%=link_to(@person.full_name,person_path(@person))%></h2>

<%= render 'form' %>

app/views/phones/index.html.erb
<h2>phones for <%=link_to(@person.full_name,person_path(@person))%></h1>
<% if !@phones.empty? %>
  <ul>
    <% @phones.each do |e| %>
      <li>
        <%= link_to(e.display_text,person_phones_path(@person,e)) %>
        <%= link_to("[edit]",edit_person_phone_path(@person,e), method: :get) %>
        <%= link_to("[delete]",person_phones_path(@person,e), method: :delete, data: { confirm: 'Are you sure?' }) %>
      </li>
    <%end%>
  </ul>
<%end%>
<h4>
  <div class="new_item button_actions"><%= link_to("New phone",new_person_phone_path) %></div>
</h4>

app/views/phones/new.html.erb
<h2>New phone for <%=link_to(@person.full_name,person_path(@person))%></h1>

<% if @phone.errors.any? %>
  <ul>
    <% @phone.errors.full_messages.each do |error_msg| %>
    <li><%= error_msg %></li>
    <% end %>
  </ul>
<% end %>

<%= render 'form' %>

app/views/phones/show.html.erb
<h2>Info about ...</h2>
<%="Person: #{@person.full_name}"%>
<%= @phone.display_text %>
<%= link_to("[edit]",edit_person_phone_path(@person,@phone), method: :get) %>
<%= link_to("[delete]",person_phones_path(@person,@phone), method: :delete, data: { confirm: 'Are you sure?' }) %>
<h4>
  <div class="button_actions"><%= link_to("This person phones",person_phones_path(@person)) %></div>
</h4>

app/views/shared/_people_list.html.erb
<ul>
<% @people.each do |p| %>
  <li>
    <%=link_to(p.full_name,person_path(p))%>
    <%= link_to("[edit]",edit_person_path(p), method: :get) %>
    <%= link_to("[delete]",person_path(p), method: :delete, data: { confirm: 'Are you sure?' }) %>
  </li>
<%end%>
</ul>